export enum AuditAction {
  CREATE_CONTRACT = 'CREATE_CONTRACT',
  UPDATE_CONTRACT = 'UPDATE_CONTRACT',
  DELETE_CONTRACT = 'DELETE_CONTRACT',
  CONTRACT_AI_REVIEW = 'CONTRACT_AI_REVIEW',
  RISK_DETECTED = 'RISK_DETECTED',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
}
